"""Added price info to the product model.

Revision ID: 1efb22880a60
Revises: 2f35e0b2052b
Create Date: 2022-05-27 10:45:32.554895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1efb22880a60"
down_revision = "2f35e0b2052b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("price_updated_date", sa.String(length=16), nullable=True)
    )
    op.add_column("product", sa.Column("current_price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "current_price")
    op.drop_column("product", "price_updated_date")
    # ### end Alembic commands ###
