"""Dropped the comment column for products.

Revision ID: 484251bc6c49
Revises: 1efb22880a60
Create Date: 2022-05-27 10:51:34.290227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "484251bc6c49"
down_revision = "1efb22880a60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "description")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("description", sa.VARCHAR(length=128), nullable=False)
    )
    # ### end Alembic commands ###
