"""Created first table.

Revision ID: 4ef61a0da6c0
Revises: 
Create Date: 2021-08-11 21:50:23.342311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef61a0da6c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priced_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priced_product')
    # ### end Alembic commands ###
