"""Added column alt_unit_factor and renamed source to store for PricedProduct.

Revision ID: a3b1f1189c1b
Revises: b7e265c54045
Create Date: 2021-10-19 20:08:11.495076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b1f1189c1b'
down_revision = 'b7e265c54045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priced_product', sa.Column('alt_unit_factor', sa.Float(), nullable=True))
    with op.batch_alter_table('priced_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store', sa.String(length=64), nullable=True))
    op.execute(
        '''
        UPDATE priced_product
        SET store=source
        '''
    )
    with op.batch_alter_table('priced_product', schema=None) as batch_op:
        batch_op.drop_column('source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priced_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=64), nullable=True)),
    op.execute(
        '''
        UPDATE priced_product
        SET source=store
        '''
    )
    with op.batch_alter_table('priced_product', schema=None) as batch_op:
        batch_op.drop_column('store')
        batch_op.drop_column('alt_unit_factor')
    # ### end Alembic commands ###
