"""Added relation from Product to PriceTrend.

Revision ID: a51002b41e4d
Revises: 14e2354a073c
Create Date: 2022-06-16 21:33:40.928859

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a51002b41e4d"
down_revision = "14e2354a073c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price_trend", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_price_trend_product_id_product", "product", ["product_id"], ["id"]
        )

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column(
            "store", existing_type=sa.VARCHAR(length=64), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column(
            "store", existing_type=sa.VARCHAR(length=64), nullable=True
        )

    with op.batch_alter_table("price_trend", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_price_trend_product_id_product", type_="foreignkey"
        )

    # ### end Alembic commands ###
